import 'custom-pages';
import '@material/mwc-drawer';
import '@material/mwc-fab';
import '@material/mwc-button';
import '@material/mwc-icon-button';
import '@material/mwc-top-app-bar-fixed';
import './elements/darkmode/element.js';
import '@material/mwc-list';
import '@vandeurenglenn/flex-elements';
import '@vandeurenglenn/lit-elements/theme.js';
import '@material/web/fab/branded-fab.js';
import '@material/web/icon/icon.js';
declare const _default: void;
export default _default;
